# This is a basic workflow to help you get started with Actions
name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v14"
        with:
          default: 2.7.18
          versions: 3.8.16
          command: pyenv -v
      - name: Cache eggs
        uses: actions/cache@v4
        env:
          cache-name: cache-eggs
        with:
          path: ~/.buildout/eggs
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Buildout
        run: |
          pip install -r requirements.txt coverage==5.3.1
          buildout -c ci.cfg annotate
          buildout -c ci.cfg
      - name: Test
        run: |
          bin/test -t !test_cpdb
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v14"
        with:
          default: 2.7.18
          versions: 3.8.16
          command: pyenv -v
      - name: Cache eggs
        uses: actions/cache@v4
        env:
          cache-name: cache-eggs
        with:
          path: ~/.buildout/eggs
          key: ${{ runner.os }}-build-coverage-${{ env.cache-name }}
      - name: Buildout
        run: |
          pip install -r requirements.txt coverage==5.3.1
          buildout -c ci.cfg annotate
          buildout -c ci.cfg
      - name: Code-analysis
        run: |
          bin/code-analysis
      - name: Test coverage
        run: |
          bin/coverage run bin/test -t !test_cpdb
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Coveralls
        run: |
          pip3 install -U pip setuptools --no-cache-dir
          pip3 install -U "coveralls>=3.0.0" coverage==5.3.1 --no-cache-dir
      - name: Publish to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
